// <auto-generated />
using System;
using HAMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.Data.Migrations
{
    [DbContext(typeof(HamsDbContext))]
    [Migration("20250714160906_Add Authentication")]
    partial class AddAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTime(2025, 7, 14, 16, 9, 5, 558, DateTimeKind.Utc).AddTicks(9297),
                            DeptName = "Cardiology",
                            Description = "Heart & vascular care",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTime(2025, 7, 14, 16, 9, 5, 558, DateTimeKind.Utc).AddTicks(9300),
                            DeptName = "Orthopedics",
                            Description = "Bones, joints & spine",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTime(2025, 7, 14, 16, 9, 5, 558, DateTimeKind.Utc).AddTicks(9301),
                            DeptName = "Dermatology",
                            Description = "Skin & hair",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HAMS.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HAMS.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HAMS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ContactNo = "9876543210",
                            CreatedAt = new DateTime(2025, 7, 14, 16, 9, 5, 618, DateTimeKind.Utc).AddTicks(2542),
                            Email = "admin@hams.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEAHEx6HNXqAZ507XAxgdcSORyPpckiuviXhgibklF5vepo6vtdzAjOJoVMXVr0TbGQ==",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ContactNo = "9123456780",
                            CreatedAt = new DateTime(2025, 7, 14, 16, 9, 5, 674, DateTimeKind.Utc).AddTicks(2513),
                            Email = "reception@hams.com",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEPmV2LDv/rHR6si2iFiYC8vT7yymq9uga04GHlzbUjpe0RJV9uwg39efswCgWTHroQ==",
                            Role = "Receptionist"
                        });
                });

            modelBuilder.Entity("HAMS.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("HAMS.Domain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAMS.Domain.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("HAMS.Domain.Entities.Doctor", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HAMS.Domain.Entities.Patient", b =>
                {
                    b.HasOne("HAMS.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("HAMS.Domain.Entities.Patient", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HAMS.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HAMS.Domain.Entities.User", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
